permissions:
  id-token: write # Это необходимо для запроса JWT

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**' # Это позволит игнорировать изменения в файлах workflow

  release:
    types:
      - published

  # Позволяет запускать этот workflow вручную из вкладки Actions
  workflow_dispatch:

env:
  FOLDER_ID: b1go2mpo9hhnjf4vugka
  SA_ID: ci-cd-github-federation
  FUNCTION_NAME: from-github-production
  FUNCTION_RUNTIME: nodejs22
  FUNCTION_ENTRYPOINT: index.handler
  FUNCTION_MEMORY: "128mb"
  FUNCTION_SOURCEROOT: .
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v3.1.0
        with:
          yc-sa-id: ${{env.SA_ID}}
          folder-id: ${{env.FOLDER_ID}}
          function-name: ${{env.FUNCTION_NAME}}
          runtime: ${{env.FUNCTION_RUNTIME}}
          entrypoint: ${{env.FUNCTION_ENTRYPOINT}}
          memory: ${{env.FUNCTION_MEMORY}}
          source-root: ${{env.FUNCTION_SOURCEROOT}}
          include: |
            **/*.json
            **/*.js